=== Maithilish/gotz/src/main/resources/schema/gotz.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="qualified" version="1.0"
    targetNamespace="http://codetab.org/gotz" xmlns:tns="http://codetab.org/gotz"
    xmlns:xf="http://codetab.org/xfield" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:import namespace="http://codetab.org/xfield"
        schemaLocation="xfield.xsd" />

    <xs:element name="wrapper" type="tns:wrapper" />

    <xs:element name="fields" type="tns:fields" />

    <xs:element name="locator" type="tns:locator" />

    <xs:element name="locators" type="tns:locators" />

    <xs:element name="document" type="tns:document" />

    <xs:element name="bean" type="tns:bean" />

    <xs:element name="beans" type="tns:beans" />

    <xs:element name="datadefs" type="tns:dataDefs" />

    <xs:element name="datadef" type="tns:dataDef" />

    <xs:element name="axis" type="tns:dAxis" />

    <xs:element name="member" type="tns:dMember" />

    <xs:element name="filter" type="tns:dFilter" />

    <xs:complexType name="wrapper">
        <xs:sequence>
            <xs:any processContents="lax" minOccurs="0"
                maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fieldsBase" abstract="true">
        <xs:sequence />
    </xs:complexType>

    <xs:complexType name="field">
        <xs:complexContent>
            <xs:extension base="tns:fieldsBase">
                <xs:sequence />
                <xs:attribute name="name" type="xs:string" />
                <xs:attribute name="value" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="fields">
        <xs:complexContent>
            <xs:extension base="tns:fieldsBase">
                <xs:group ref="tns:fields" />
                <xs:attribute name="name" type="xs:string" />
                <xs:attribute name="value" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- group of fields and field (composite pattern) -->
    <xs:group name="fields">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="field" type="tns:field" />
                <xs:element name="fields" type="tns:fields" />
            </xs:choice>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="base" abstract="true">
        <xs:sequence>
            <xs:element name="id" type="xs:long" minOccurs="0"
                maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="locators">
        <xs:sequence>
            <xs:element name="locator" minOccurs="0"
                maxOccurs="unbounded" type="tns:locator" />
            <xs:element ref="tns:locators" minOccurs="0"
                maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="group" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="locator" final="extension restriction">
        <xs:complexContent>
            <xs:extension base="tns:base">
                <xs:sequence>
                    <xs:group ref="tns:fields" />
                    <xs:element name="xField" type="xf:xField"
                        minOccurs="0" maxOccurs="1" />
                    <xs:element name="documents" type="tns:document"
                        minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
                <xs:attribute name="url" type="xs:string" />
                <xs:attribute name="group" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="document">
        <xs:complexContent>
            <xs:extension base="tns:base">
                <xs:sequence>
                    <xs:element name="documentObject" type="xs:anyType"
                        minOccurs="0" />
                </xs:sequence>
                <xs:attribute name="fromDate" type="xs:dateTime" />
                <xs:attribute name="toDate" type="xs:dateTime" />
                <xs:attribute name="url" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="beans">
        <xs:sequence>
            <xs:element ref="tns:bean" minOccurs="0"
                maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bean">
        <xs:sequence />
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="className" type="xs:string"
            use="required" />
        <xs:attribute name="xmlFile" type="xs:string" use="required" />
        <xs:attribute name="schemaFile" type="xs:string"
            use="optional" />
    </xs:complexType>

    <xs:complexType name="dataDefs">
        <xs:sequence>
            <xs:element ref="tns:datadef" minOccurs="0"
                maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dataDef">
        <xs:complexContent>
            <xs:extension base="tns:base">
                <xs:sequence>
                    <xs:group ref="tns:fields" />
                    <xs:element ref="tns:axis" minOccurs="0"
                        maxOccurs="unbounded" />
                </xs:sequence>
                <xs:attribute name="fromDate" type="xs:dateTime" />
                <xs:attribute name="toDate" type="xs:dateTime" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="dAxis">
        <xs:complexContent>
            <xs:extension base="tns:base">
                <xs:sequence>
                    <xs:group ref="tns:fields" />
                    <xs:element ref="tns:member" minOccurs="0"
                        maxOccurs="unbounded" />
                    <xs:element ref="tns:filter" minOccurs="0" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="dMember">
        <xs:complexContent>
            <xs:extension base="tns:base">
                <xs:sequence>
                    <xs:group ref="tns:fields" />
                </xs:sequence>
                <xs:attribute name="axis" type="xs:string" />
                <xs:attribute name="index" type="xs:int" />
                <xs:attribute name="match" type="xs:string" />
                <xs:attribute name="order" type="xs:int" />
                <xs:attribute name="value" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="dFilter">
        <xs:complexContent>
            <xs:extension base="tns:base">
                <xs:sequence>
                    <xs:group ref="tns:fields" />
                </xs:sequence>
                <xs:attribute name="axis" type="xs:string" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== Maithilish/gotz/src/test/resources/itest/itc/price/datadef.xml
<?xml version="1.0" encoding="UTF-8"?>
<datadefs xmlns="http://codetab.org/gotz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://codetab.org/gotz gotz.xsd">
    <datadef name="price">
        <axis name="col">
            <fields name="group" value="script">
                <field name="script" value="configs.getRunDateTime()" />
            </fields>
            <member name="date" />
        </axis>
        <axis name="row">
            <member name="Price" value="Price" />
        </axis>
        <axis name="fact">
            <fields name="group" value="query">
                <field name="region" value="div#Nse_Prc_tick_div" />
                <field name="field" value="*" />
            </fields>
        </axis>
    </datadef>
</datadefs>

=== Maithilish/gotz/src/test/resources/itest/itc/quotepage/htmlunit/datadef.xml
<?xml version="1.0" encoding="UTF-8"?>

<datadefs xmlns="http://codetab.org/gotz" xmlns:xf="http://codetab.org/xfields"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://codetab.org/gotz gotz.xsd">

    <datadef name="quotePage">
        <axis name="col">
            <xf:fields>
                <xf:script script="document.getFromDate()" />
            </xf:fields>
            <member name="date" />
        </axis>
        <axis name="row">
            <xf:fields>
                <xf:query region="//*[@id='mktdet_2']"
                    field="div/div/div[starts-with(child::text(),'%{row.match}')]/child::text()" />
            </xf:fields>
            <member name="MC" match="MARKET CAP" />
            <member name="EPS" match="EPS (TTM)" />
            <member name="PE" match="P/E" />
            <member name="PC" match="P/C" />
            <member name="BV" match="BOOK VALUE" />
            <member name="PB" match="PRICE/BOOK" />
            <member name="DIV" match="DIV (%)" />
            <member name="DY" match="DIV YIELD" />
            <member name="FV" match="FACE VALUE" />
            <member name="IND PE" match="INDUSTRY P/E" />
        </axis>
        <axis name="fact">
            <xf:fields>
                <xf:query region="//*[@id='mktdet_2']"
                    field="div/div/div[starts-with(child::text(),'%{row.match}')]/following-sibling::div[1]" />
            </xf:fields>
        </axis>
    </datadef>

</datadefs>

=== Maithilish/gotz/src/test/resources/itest/housetax/datadef.xml
<?xml version="1.0" encoding="UTF-8"?>
<datadefs xmlns="http://codetab.org/gotz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://codetab.org/gotz gotz.xsd">
    <datadef name="taxtable">
        <axis name="col">
            <fields name="group" value="query">
                <field name="region" value="table:contains(Taxes)" />
                <field name="field"
                    value="tbody > tr:nth-child(1) > th:nth-child(%{col.index})" />
            </fields>
            <member name="year" index="2">
                <!-- <field name="indexRange" value="1-1" /> -->
                <field name="breakAfter" value="2017" />
            </member>
        </axis>
        <axis name="row">
            <fields name="group" value="query">
                <field name="region" value="table:contains(Taxes)" />
                <field name="field"
                    value="tbody > tr:nth-child(%{row.index}) > td:nth-child(1)" />
            </fields>
            <member name="item" index="2">
                <!-- <field name="indexRange" value="1-1" /> -->
                <field name="breakAfter" value="GF" />
            </member>
            <filter axis="row">
                <fields name="group" value="value">
                    <field name="blank" value="" />
                </fields>
            </filter>
        </axis>
        <axis name="fact">
            <fields name="group" value="query">
                <field name="region" value="table:contains(Taxes)" />
                <field name="field"
                    value="tbody > tr:nth-child(%{row.index}) > td:nth-child(%{col.index})" />
            </fields>
        </axis>
    </datadef>
</datadefs>

=== Maithilish/gotz/src/test/resources/itest/itc/pl/htmlunit/datadef.xml
<?xml version="1.0" encoding="UTF-8"?>
<datadefs xmlns="http://codetab.org/gotz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://codetab.org/gotz gotz.xsd">
    <datadef name="pl">
        <axis name="col">
            <fields name="group" value="query">
                <field name="region"
                    value="//table//*[count(*)=0 and contains(.,'Employee Cost')]/ancestor::table[1]" />
                <field name="field" value="*//tr[1]/td[%{col.index}+1]" />
            </fields>
            <member name="year">
                <field name="indexRange" value="1-5" />
            </member>
        </axis>
        <axis name="row">
            <fields name="group" value="query">
                <field name="region"
                    value="//table//*[count(*)=0 and contains(.,'Employee Cost')]/ancestor::table[1]" />
                <field name="field" value="*//tr[%{row.index}+0]/td[1]" />
            </fields>
            <member name="item" index="6">
                <!-- <field name="indexRange" value="1-37" /> -->
                <field name="breakAfter" value="Book Value (Rs)" />
            </member>
            <filter axis="row">
                <fields name="group" value="value">
                    <field name="blank" value="" />
                    <field name="f1" value="Expenditure" />
                    <field name="f2" value="Per share data (annualised)" />
                </fields>
            </filter>
        </axis>
        <axis name="fact">
            <fields name="group" value="query">
                <field name="region"
                    value="//table//*[count(*)=0 and contains(.,'Employee Cost')]/ancestor::table[1]" />
                <field name="field"
                    value="*//*[.='%{row.value}']/following-sibling::td[%{col.index}]" />
            </fields>
        </axis>
    </datadef>
</datadefs>

=== Maithilish/gotz/src/main/resources/defs/simple/html/datadef.xml
<?xml version="1.0" encoding="UTF-8"?>
<datadefs xmlns="http://codetab.org/gotz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://codetab.org/gotz gotz.xsd">
    <datadef name="taxestable">
        <field name="logstate" value="true" />
        <axis name="col">
            <fields name="group" value="query">
                <field name="region" value="//table" />
                <field name="field" value="*//tr[1]/th[%{col.index}+1]" />
            </fields>
            <member name="year">
                <!-- <field name="indexRange" value="1-1" /> -->
                <field name="breakAfter" value="2017" />
            </member>
        </axis>
        <axis name="row">
            <fields name="group" value="query">
                <field name="region" value="//table" />
                <field name="field" value="*//tr[%{row.index}+1]/td[1]" />
            </fields>
            <member name="item">
                <!-- <field name="indexRange" value="1-1" /> -->
                <field name="breakAfter" value="GF" />
            </member>
            <filter axis="row">
                <fields name="group" value="value">
                    <field name="blank" value="" />
                </fields>
            </filter>
        </axis>
        <axis name="fact">
            <fields name="group" value="query">
                <field name="region" value="//table" />
                <field name="field"
                    value="*//*[.='%{row.value}']/following-sibling::td[%{col.index}]" />
            </fields>
        </axis>
    </datadef>
</datadefs>

=== Maithilish/gotz/src/test/resources/itest/itc/pl/datadef.xml
<?xml version="1.0" encoding="UTF-8"?>
<datadefs xmlns="http://codetab.org/gotz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://codetab.org/gotz gotz.xsd">
    <datadef name="pl">
        <axis name="col">
            <fields name="group" value="query">
                <field name="region" value="table:contains(Employee Cost)" />
                <field name="field"
                    value="tr:nth-child(1) > td:nth-child(%{col.index})" />
            </fields>
            <member name="year">
                <field name="indexRange" value="2-6" />
            </member>
        </axis>
        <axis name="row">
            <fields name="group" value="query">
                <field name="region" value="table:contains(Employee Cost)" />
                <field name="field"
                    value="tr:nth-child(%{row.index}) > td:nth-child(1)" />
            </fields>
            <member name="item" index="6">
                <!-- <field name="indexRange" value="1-37" /> -->
                <field name="breakAfter" value="Book Value (Rs)" />
            </member>
            <filter axis="row">
                <fields name="group" value="value">
                    <field name="blank" value="" />
                    <field name="f1" value="Expenditure" />
                    <field name="f2" value="Per share data (annualised)" />
                </fields>
            </filter>
        </axis>
        <axis name="fact">
            <fields name="group" value="query">
                <field name="region" value="table:contains(Employee Cost)" />
                <field name="field"
                    value="tr:nth-child(%{row.index}) > td:nth-child(%{col.index})" />
            </fields>
        </axis>
    </datadef>
</datadefs>

=== Maithilish/gotz/src/main/resources/defs/mc/htmlunit/datadef.xml
<?xml version="1.0" encoding="UTF-8"?>
<datadefs xmlns="http://codetab.org/gotz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://codetab.org/gotz gotz.xsd">
    <datadef name="finlocators">
        <field name="type" value="locator" />
        <fields name="member" value="bs">
            <field name="group" value="bs" />
        </fields>
        <fields name="member" value="pl">
            <field name="group" value="pl" />
        </fields>
        <axis name="col">
            <fields name="group" value="script">
                <field name="script" value="configs.getRunDateTime()" />
            </fields>
            <member name="date" />
        </axis>
        <axis name="row">
            <fields name="group" value="query">
                <field name="region" value="//*[@id='quickLinkPrc']/table" />
                <field name="field" value="//li/a[contains(.,'%{row.match}')]" />
            </fields>
            <member name="bs" match="Balance Sheet" />
            <member name="pl" match="Profit &amp; Loss" />
        </axis>
        <axis name="fact">
            <fields name="group" value="query">
                <field name="region" value="//*[@id='quickLinkPrc']/table" />
                <field name="field"
                    value="*//a[contains(.,'%{row.match}')]/@href" />
            </fields>
            <fields name="group" value="prefix">
                <field name="prefix" value="http://www.moneycontrol.com" />
            </fields>
        </axis>
    </datadef>
    <datadef name="bs">
        <axis name="col">
            <fields name="group" value="query">
                <field name="region"
                    value="//table//*[count(*)=0 and contains(.,'Total Share Capital')]/ancestor::table[1]" />
                <field name="field" value="*//tr[1]/td[%{col.index}+1]" />
            </fields>
            <member name="year">
                <field name="indexRange" value="1-5" />
                <!-- <field name="breakAfter" value="Mar '16" /> -->
            </member>
        </axis>
        <axis name="row">
            <fields name="group" value="query">
                <field name="region"
                    value="//table//*[count(*)=0 and contains(.,'Total Share Capital')]/ancestor::table[1]" />
                <field name="field" value="*//tr[%{row.index}+1]/td[1]" />
            </fields>
            <member name="item" index="5">
                <!-- <field name="indexRange" value="1-34" /> -->
                <field name="breakAfter" value="Book Value (Rs)" />
            </member>
            <filter axis="row">
                <fields name="group" value="value">
                    <field name="blank" value="" />
                    <field name="f1" value="Sources Of Funds" />
                    <field name="f2" value="Application Of Funds" />
                </fields>
            </filter>
        </axis>
        <axis name="fact">
            <fields name="group" value="query">
                <field name="region"
                    value="//table//*[count(*)=0 and contains(.,'Total Share Capital')]/ancestor::table[1]" />
                <field name="field"
                    value="*//*[.='%{row.value}']/following-sibling::td[%{col.index}]" />
            </fields>
        </axis>
    </datadef>
    <datadef name="pl">
        <axis name="col">
            <fields name="group" value="query">
                <field name="region"
                    value="//table//*[count(*)=0 and contains(.,'Employee Cost')]/ancestor::table[1]" />
                <field name="field" value="*//tr[1]/td[%{col.index}+1]" />
            </fields>
            <member name="year">
                <field name="indexRange" value="1-5" />
            </member>
        </axis>
        <axis name="row">
            <fields name="group" value="query">
                <field name="region"
                    value="//table//*[count(*)=0 and contains(.,'Employee Cost')]/ancestor::table[1]" />
                <field name="field" value="*//tr[%{row.index}+0]/td[1]" />
            </fields>
            <member name="item" index="6">
                <!-- <field name="indexRange" value="1-37" /> -->
                <field name="breakAfter" value="Book Value (Rs)" />
            </member>
            <filter axis="row">
                <fields name="group" value="value">
                    <field name="blank" value="" />
                    <field name="f1" value="Expenditure" />
                    <field name="f2" value="Per share data (annualised)" />
                </fields>
            </filter>
        </axis>
        <axis name="fact">
            <fields name="group" value="query">
                <field name="region"
                    value="//table//*[count(*)=0 and contains(.,'Employee Cost')]/ancestor::table[1]" />
                <field name="field"
                    value="*//*[.='%{row.value}']/following-sibling::td[%{col.index}]" />
            </fields>
        </axis>
    </datadef>
    <datadef name="quotePage">
        <axis name="col">
            <fields name="group" value="script">
                <field name="script" value="document.getFromDate()" />
            </fields>
            <member name="date" />
        </axis>
        <axis name="row">
            <fields name="group" value="query">
                <field name="region" value="//*[@id='mktdet_2']" />
                <field name="field"
                    value="div/div/div[starts-with(child::text(),'%{row.match}')]/child::text()" />
            </fields>
            <member name="MC" match="MARKET CAP" />
            <member name="EPS" match="EPS" />
            <member name="PE" match="P/E" />
            <member name="PC" match="P/C" />
            <member name="BV" match="BOOK VALUE" />
            <member name="PB" match="PRICE/BOOK" />
            <member name="DIV" match="DIV (%)" />
            <member name="DY" match="DIV YIELD" />
            <member name="FV" match="FACE VALUE" />
            <member name="IND PE" match="INDUSTRY P/E" />
        </axis>
        <axis name="fact">
            <fields name="group" value="query">
                <field name="region" value="//*[@id='mktdet_2']" />
                <field name="field"
                    value="div/div/div[starts-with(child::text(),'%{row.match}')]/following-sibling::div[1]" />
            </fields>
        </axis>
    </datadef>
    <datadef name="price">
        <axis name="col">
            <fields name="group" value="script">
                <field name="script" value="document.getFromDate()" />
            </fields>
            <member name="date" />
        </axis>
        <axis name="row">
            <member name="Price" value="Price" />
        </axis>
        <axis name="fact">
            <fields name="group" value="query">
                <field name="region" value="//*[@id='Nse_Prc_tick']" />
                <field name="field" value="strong" />
            </fields>
        </axis>
    </datadef>
</datadefs>

=== Maithilish/gotz/src/main/resources/perfdefs/mc/one-locator/datadef.xml
<?xml version="1.0" encoding="UTF-8"?>
<datadefs xmlns="http://codetab.org/gotz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://codetab.org/gotz gotz.xsd">
    <datadef name="bs">
        <axis name="col">
            <fields name="group" value="query">
                <field name="region" value="table:contains(Sources Of Funds)" />
                <field name="field" value="tr:nth-child(1) > td:nth-child(%{col.index})" />
            </fields>
            <member name="year">
                <field name="indexRange" value="2-6" />
                <!-- <field name="breakAfter" value="Mar '16" /> -->
            </member>
        </axis>
        <axis name="row">
            <fields name="group" value="query">
                <field name="region" value="table:contains(Sources Of Funds)" />
                <field name="field" value="tr:nth-child(%{row.index}) > td:nth-child(1)" />
            </fields>
            <member name="item" index="5">
                <!-- <field name="indexRange" value="1-34" /> -->
                <field name="breakAfter" value="Book Value (Rs)" />
            </member>
            <filter axis="row">
                <fields name="group" value="value">
                    <field name="blank" value="" />
                    <field name="f1" value="Sources Of Funds" />
                    <field name="f2" value="Application Of Funds" />
                </fields>
            </filter>
        </axis>
        <axis name="fact">
            <fields name="group" value="query">
                <field name="region" value="table:contains(Sources Of Funds)" />
                <field name="field"
                    value="tr:nth-child(%{row.index}) > td:nth-child(%{col.index})" />
            </fields>
        </axis>
    </datadef>
</datadefs>
